KEYWORD_MAP = {
    "fever": ["fever", "bukhar", "बुखार", "taap", "ताप", "temperature"],
    "high_fever": ["high fever", "tez bukhar", "तेज़ बुखार", "39", "40", "104", "103", "102"],
    "chills": ["chill", "thandi", "ठंड", "kaanpna", "काँपना", "shiver", "kamp"],
    "headache": ["headache", "sir dard", "सिर दर्द", "sardard", "सरदर्द", "head pain"],
    "severe_headache": ["severe headache", "bahut sir dard", "बहुत सिर दर्द", "tez sardard"],
    "body_ache": ["body ache", "badan dard", "बदन दर्द", "body pain", "sharir dard", "शरीर दर्द"],
    "joint_pain": ["joint pain", "jod dard", "जोड़ दर्द", "gathiya", "गठिया", "joint"],
    "muscle_pain": ["muscle pain", "maaspeshi dard", "मांसपेशी दर्द", "muscle"],
    "cough": ["cough", "khansi", "खांसी", "khaansi"],
    "chronic_cough": ["chronic cough", "purani khansi", "पुरानी खांसी", "lambi khansi", "weeks cough", "mahino se khansi"],
    "sore_throat": ["sore throat", "gala dard", "गला दर्द", "gala kharab", "गला खराब", "throat"],
    "runny_nose": ["runny nose", "naak behna", "नाक बहना", "naak beh raha", "nose running"],
    "sneezing": ["sneez", "chheenk", "छींक"],
    "difficulty_breathing": ["difficulty breathing", "saans lene mein taklif", "सांस लेने में तकलीफ", "breathless", "saans nahi", "cant breathe"],
    "rapid_breathing": ["rapid breath", "tez saans", "तेज़ सांस", "fast breath"],
    "chest_pain": ["chest pain", "seena dard", "सीना दर्द", "chhati dard", "छाती दर्द", "chest"],
    "abdominal_pain": ["stomach pain", "pet dard", "पेट दर्द", "abdominal", "pet mein dard", "tummy"],
    "nausea": ["nausea", "ji machlana", "जी मचलाना", "ulti jaisa", "मतली", "queasy"],
    "vomiting": ["vomit", "ulti", "उल्टी"],
    "diarrhea": ["diarrhea", "dast", "दस्त", "loose motion", "पतला मल", "loose stool", "watery stool"],
    "rash": ["rash", "daane", "दाने", "skin rash", "चकत्ते", "lal daane", "spots on skin"],
    "eye_pain": ["eye pain", "aankh dard", "आँख दर्द", "aankh mein dard", "eyes hurt"],
    "dark_urine": ["dark urine", "peela peshab", "गहरा पेशाब", "brown urine"],
    "blood_in_sputum": ["blood cough", "khoon khansi", "खून खांसी", "blood sputum", "balgam mein khoon"],
    "night_sweats": ["night sweat", "raat ko paseena", "रात को पसीना"],
    "weight_loss": ["weight loss", "vajan ghatna", "वज़न घटना", "patla hona", "getting thin"],
    "fatigue": ["tired", "thakan", "थकान", "fatigue", "kamzori", "कमज़ोरी", "exhausted"],
    "weakness": ["weak", "kamzor", "कमज़ोर", "no energy", "shakti nahi"],
    "dizziness": ["dizzy", "chakkar", "चक्कर", "sir ghoomna", "सिर घूमना", "lightheaded"],
    "sweating": ["sweat", "paseena", "पसीना", "bahut paseena", "profuse sweat"],
    "confusion": ["confus", "behoshi", "samajh nahi", "disoriented", "confused"],
    "bleeding": ["bleed", "khoon", "खून", "khoon behna", "blood coming"],
    "pale_skin": ["pale", "peela", "पीला", "safed", "rang ud gaya", "pallor"],
    "dehydration_signs": ["dehydrat", "paani ki kami", "पानी की कमी", "pyaas", "प्यास", "thirsty", "dry mouth", "sookha muh"],
}
